version: "3.7"

services:

  epidemicpoker_gateway:
    container_name: epidemicpoker_gateway
    build:
      context: ./gateway
      target: prod
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    networks:
      - epidemicpoker

  epidemicpoker_gs:
    container_name: epidemicpoker_gs
    restart: always
    build:
      context: ./gs
      target: prod
      args:
        - SHARD_NAME=1
        - JWT_SECRET="super.super.secret"
    networks:
      - epidemicpoker

  epidemicpoker_balancer:
    container_name: epidemicpoker_balancer
    build:
      context: ./balancer
    environment:
      - HTTP_PORT=8080
    networks:
      - epidemicpoker

networks:
  epidemicpoker:
    name: epidemicpoker
    driver: bridge