version: "3.7"

services:

  epidemicpoker_gateway:
    container_name: epidemicpoker_gateway
    build:
      context: ./gateway
      target: prod
    restart: always
    ports:
      - ${HTTP_PORT}:8080
    networks:
      - epidemicpoker

  epidemicpoker_gs:
    container_name: epidemicpoker_gs
    build:
      context: ./gs
      target: prod

networks:
  epidemicpoker:
    name: epidemicpoker
    driver: bridge