version: "3.7"

services:

  epidemicpoker_gateway:
    build:
      target: base
#    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - epidemicpoker-frontend-build:/var/www/html/build:ro
      - ./frontend/src/public:/var/www/html/public:ro

  epidemicpoker_frontend:
    container_name: epidemicpoker_frontend
    image: epidemicpoker_frontend
    volumes:
      # Code
      - ./frontend/src:/app/epidemicpoker:delegated
      # Build Output
      - epidemicpoker-frontend-build:/app/epidemicpoker/build
      # Ignore Node Modules
      - epidemicpoker-frontend-node:/app/epidemicpoker/node_modules
    networks:
      - epidemicpoker

  epidemicpoker_gs:
    build:
      target: dev
      args:
        - GS_XDEBUG_ACTIVE=${GS_XDEBUG_ACTIVE}
    volumes:
      - ./gs/src:/app/epidemicpoker:delegated

volumes:
  epidemicpoker-frontend-build:
  epidemicpoker-frontend-node: